terraform/01_core_cluster/main.tf
terraform/modules/a_record/main.tf
terraform/modules/a_record/variables.tf
terraform/modules/public_ip/outputs.tf

When terraforming a new kubernetes environment, a wildcard DNS A record will be created pointing to a reserved public IP.
The A record will always be created in the demo.catena-x.net DNS Zone.
The wildcard will include the environment name, like for example '*.core', which will result in *.core.demo.catena-x.net as Domain.
Steps that have to follow this PR: 
- Fix the already existing wildcard record to point to the reserved public IP
- assign the public IP to the ingress controller of the core environment

feat: add dns a record for kubernetes clusters in terraform

---

environments/hotel-budapest/avp-secrets/bpdm-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/data-format-transformer-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/data-integrity-demonstrator-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/devsecops-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/edc-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/essential-services-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/managed-identity-wallets-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/material-pass-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/portal-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/semantics-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/template-team-vault-secret.yaml.example
environments/hotel-budapest/avp-secrets/traceability-dft-team-vault-secret.yaml
environments/hotel-budapest/avp-secrets/traceablity-irs-team-vault-secret.yaml

This PR names all the team secrets for ArgoCD Vault Plugin the same. This will make it easier to identify the secret needed to configure the vault integration. 
Name conflicts wont happen, because every team is running in its own namespace, and so is the AVP secret

Use same AVP secret name for each team

---

apps/argocd/base/argocd-rbac-cm.yaml

Product-team member were not able to:
- pick targetRepository path from sugestion list
- pick destination from sugestion list
Fix was to adjust the default rbac rules in `argocd-rbac-cm.yaml`:
- still deny access to all _applications_ 
- allow get cluster resources
- allow get repositories
The hard deny on all resources prevented to receive these sugestion lists (example for _Path_):
As the role name _none_ doesn't match any longer, renamed policy to _minimal_.

renamed default policy to minimal

---

apps/argocd/overlays/hotel-budapest/configmap/argo-cm.yaml
apps/argocd/overlays/hotel-budapest/ingress/ingress-argocd.yaml

`argocd-cm.yaml` and `ingress-argocd.yaml` has been adjusted to new FQDN argo.int.demo.catena-x.net. Later on we've to rename the overlays  & co specifics

FQDN for "hotel budapest" changed to argo.int.demo.catena-x.net

---

environments/dev/argo-projects/product-bpdm.yaml
environments/dev/argo-projects/product-catenax-at-home.yaml
environments/dev/argo-projects/product-data-format-transformer.yaml
environments/dev/argo-projects/product-data-integritiy-demonstrator.yaml
environments/dev/argo-projects/product-edc.yaml
environments/dev/argo-projects/product-essential-services.yaml
environments/dev/argo-projects/product-managed-identity-wallets.yaml
environments/dev/argo-projects/product-material-pass.yaml
environments/dev/argo-projects/product-portal.yaml
environments/dev/argo-projects/product-semantics.yaml
environments/dev/argo-projects/product-test-data-generator.yaml
environments/dev/argo-projects/product-traceability-dft.yaml
environments/dev/argo-projects/product-traceability-irs.yaml
environments/dev/argo-repos/product-semantics-repo.yaml
environments/dev/argo-repos/product-test-data-generator-repo.yaml
environments/dev/avp-secrets/bpdm-team-vault-secret.yaml
environments/dev/avp-secrets/catenax-at-home-team-vault-secret.yaml
environments/dev/avp-secrets/data-format-transformer-team-vault-secret.yaml
environments/dev/avp-secrets/data-integrity-demonstrator-team-vault-secret.yaml
environments/dev/avp-secrets/edc-team-vault-secret.yaml
environments/dev/avp-secrets/essential-services-team-vault-secret.yaml
environments/dev/avp-secrets/managed-identity-wallets-team-vault-secret.yaml
environments/dev/avp-secrets/material-pass-team-vault-secret.yaml
environments/dev/avp-secrets/portal-team-vault-secret.yaml
environments/dev/avp-secrets/semantics-team-vault-secret.yaml
environments/dev/avp-secrets/template-team-vault-secret.yaml.example
environments/dev/avp-secrets/test-data-generator-team-vault-secret.yaml
environments/dev/avp-secrets/traceability-dft-team-vault-secret.yaml
environments/dev/avp-secrets/traceablity-irs-team-vault-secret.yaml
environments/dev/kustomization.yaml

- Duplicating existing ArgoCD Projects, AVP secrets and ArgoCD repository definitions from INT to DEV
- Split EDC and catenax-at-home
- Remove -dev namespaces from projects, where existing

feat: A1ODT-508 Add initial argo projects to dev env

---

apps/argocd/base/kustomization.yaml
environments/core/applicationsets/argo-applicationset.yaml

Lift ArgoCD to v2.3.4 to cover https://github.com/argoproj/argo-cd/security/advisories/GHSA-r642-gv9p-2wjj

update ArgoCD to fix critical security issue

---

terraform/modules/vault/main.tf

enhance `token_num_uses` to fix *-config Apps at Core ArgoCD instance. PR content is already deployed via Terraform to Core instance.

Fix ArgoCD Vault Usage for *-config Apps

---

environments/core/cluster-secrets/hotel-budapest-secret.yaml

Moved Vault annotation from _hotel-budapest_ to _int_ to streamline our naming.
Created the referenced secret in new path. Old path ([devsecops/show/clusters/hotel-budapest/k8s](https://vault.demo.catena-x.net/ui/vault/secrets/devsecops/show/clusters/hotel-budapest/k8s)) will be removed, after merge to main.

Vault annotation adjustment

---

terraform/02_team_onboarding/main.tf
terraform/modules/github/main.tf

PR includes terraform code to create a new repository based on the https://github.com/actions/javascript-action template.
There is also a minor improvement for the branch protection resource. 
Problem: We want to create CODEOWNERS files on all repositories. This also adds branch protection. Branch protection can only be enabled on public repos. This lead to errors, when applying plans that created branch protection for private repos.
Now, private repos are excluded from the branch protection resource.

feat: A1ODT-504 create GitHub action repository

---

terraform/02_team_onboarding/main.tf

When applying this terraform config, then all of our repositories in the organization will have GitHub pages enabled.
We need this, to enable teams to release their helm charts via GitHub packages

Enable GitHub pages on all repositories

---

terraform/02_team_onboarding/main.tf
terraform/modules/github/main.tf
terraform/modules/github/variables.tf

This PR adds a new repo 'catena-x-release' and two teams 'release-management' and 'test-management' to our terraform configuration.
Apparently the GitHub pages settings cannot be changed on existing repos via terraform. Most likely a permission issue, but even with a token with full permissions it could not be created (404 responses). 
On the new repositories, the GitHub pages feature is enabled as expected. 
Although changing the GitHub pages setting is resulting in 404, the state is updated, so there are no changes in GitHub, but the state is altered, so that on a second run, terraform does not apply any changes.
New repo is already created (tf apply...)

feat: A1ODT-761 create release chart repo

---

apps/argocd/base/avp-argocd-cm.yaml

HELM related ArgoCD Vault plugins where unable to build/update dependencies if App is created as HELM based instead of GIT. Error was 
```
Unable to create application: 
application spec for backend-helm-test is invalid: 
InvalidSpecError: Unable to generate manifests in : 
rpc error: 
code = Unknown 
desc = `sh -c helm dependency build -n $ARGOCD_APP_NAMESPACE` failed exit status 1: 
Error: no repository definition for https://charts.bitnami.com/bitnami, https://helm.runix.net. 
Please add the missing repos via 'helm repo add'
```
Using `helm dependency update` instead of `helm dependency build` in init section of AVP definition solved the issue.

fix: change AVP init to helm dependency update to fix A1ODT-850

---

environments/beta/pull-secret/secret.yaml
environments/dev/pull-secret/secret.yaml
environments/devsecops-testing/pull-secret/secret.yaml
environments/hotel-budapest/pull-secret/secret.yaml
environments/pre-prod/pull-secret/secret.yaml

Reflector specific annotation `reflector.v1.k8s.emberstack.com/reflects` in source secrets leads in deletion of source secret by reflector instead of reflect it to specific namespaces.
How to reproduce (done on cx-devsecops-testing-aks):
- Set `replicas` in Reflector deployment to `0` to temp. disable reflector.
- ArgoCD will immediately create the source secret in default namespace that contains the misplaced annotation.
- Set `replicas` in Reflector deployment back to `1` to enable reflector again.
- Source secret gets immediately deleted. 
This is the reason why the secret appears as flapping (OutOfSync <-> Sync).
Using the correct set of annotations fix the problem.

fix: fix reflector annotation for pull-secret, dos2unix

---

environments/pre-prod/argo-projects/product-bpdm.yaml
environments/pre-prod/argo-projects/product-daps.yaml
environments/pre-prod/argo-projects/product-managed-identity-wallets.yaml
environments/pre-prod/argo-projects/product-portal.yaml
environments/pre-prod/argo-projects/product-sldt.yaml

added policy to enable teams to view app deployed to _default_ project.

Fix Pre-Prod project role/policy

---

terraform/100_team_onboarding/main.tf

These terraform changes will add all Release 2 wave A product teams as collaborator to our deployment repo.
This will enable 'write' access, so teams can open PRs from that repository without creating a fork.

chore: add wave-a product-teams as collaborator to deploy repo; A1ODT-933

---

apps/argocd/base/plugins/argo-vault-plugin.yaml
environments/core/applicationsets/argo-applicationset.yaml

Bump AVP version to latest v0.13.0 and change ArgoCD Tag to be able to test it on DEVSECOPS-TESTING k8s cluster

Build/A1ODT-880: update avp

---

apps/vault/Chart.yaml

feat: bump DEX chart to 0.12.1 (= dex v2.35.3) to fix security issue

---

terraform/100_team_onboarding/.terraform.lock.hcl
terraform/100_team_onboarding/main.tf

The catena-x-release repository is obsolete. Moved to the forked tractus-x-release repository and it's already ahead.
See changes with `terraform plan`

feat: remove obsolete catena-x-release repo

---

environments/dev/argo-repos/product-esc-backbone-blockexplorer.yaml
environments/hotel-budapest/argo-repos/product-esc-backbone-blockexplorer.yaml

Add product-esc-backbone-blockexplorer repo to our Argo CD instances (DEV and INT).

chore: add blockexplorer repo to Argo CD #A1ODT-964

---

terraform/100_team_onboarding/main.tf

Two commits:
- one to fix the vault stuff for new team r-strategy-assistant
- one to fix TF state out of sync regarding dft-frontend gh-pages
`terraform plan`output:
```shell
- resource "vault_approle_auth_backend_role" "product-team-approles" {
- backend                 = "approle" -> null
- bind_secret_id          = true -> null
- id                      = "auth/approle/role/product-r-strategy-assistant" -> null
- role_id                 = "a0eb2a8f-1d66-7730-7852-5404c58e6de1" -> null
- role_name               = "product-r-strategy-assistant" -> null
- secret_id_bound_cidrs   = [] -> null
- secret_id_num_uses      = 0 -> null
- secret_id_ttl           = 0 -> null
- token_bound_cidrs       = [] -> null
- token_explicit_max_ttl  = 0 -> null
- …
```

chore: fix vault r-strategy-assistant and TF state

---

environments/core/applicationsets/argo-applicationset.yaml

Bumped `targetRevision` for production clusters in ArgoCD ApplicationSet.

Rollout ArgoCD v2.3.11 to production

---

terraform/100_team_onboarding/main.tf

Enable GH Pages for proper useage of Chart Releaser action.
`Terraform plan` looks pretty good:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
~ resource "github_repository" "repositories" {
id                          = "product-sd-hub"
name                        = "product-sd-hub"
+ pages {
+ source {
+ branch = "gh-pages"
+ path   = "/"
}
}
}
Plan: 0 to add, 1 to change, 0 to destroy.
```
`terraform apply` will be applied after merging to `main` branch.

chore: enable GH Pages for repo sd-hub for Chart releaser action

---

terraform/100_team_onboarding/.terraform.lock.hcl
terraform/100_team_onboarding/main.tf

- Forking https://github.com/eclipse-tractusx/portal-assets to catenax-ng/tx-portal-assets
- Changing product-sd-hub page branch to `main` as they use Pages for documentation instead of Helm repo
`terraform plan` output:
```plan
~ resource "github_repository" "repositories" {
id                          = "product-sd-hub"
name                        = "product-sd-hub"
~ pages {
~ source {
~ branch = "main" -> "gh-pages"
}
}
}
~ resource "github_repository" "repositories" {
~ auto_init                   = false -> true
id                          = "tx-portal-assets"
name                        = "tx-portal-assets"
}
+ resource "github_team_repository" "team-repository-access" {
+ etag       = (known after apply)
+ id         = (known after …
```

chore: add tx-portal-assets fork repo

---

apps/argocd/base/rbac-secret-access.yaml

In ArgoCD 2.4 a new `ServiceAccount` was introduced: https://github.com/argoproj/argo-cd/pull/9301
This would break the AVP plugin as the new `ServiceAccount` does not have get access to `Secrets` in argocd namespace. Adding new `RoleBinding` to this account would solve the access issue.
ArgoCD issue with possible solution: https://github.com/argoproj/argo-cd/issues/10499#issuecomment-1315917334
I've also left the `RoleBinding` for the default `ServiceAccount` to avoid compatibility issues.

fix: add rolebinding to argocd-repo-server user

---

environments/beta/argo-projects/product-managed-identity-wallets.yaml
environments/beta/avp-secrets/managed-identity-wallets-team-vault-secret.yaml
environments/beta/kustomization.yaml

Team requested `argo project` and access to the `beta environment`. See chat on the [CoP Channel](https://teams.microsoft.com/l/message/19:9a3c4a05a3514d07b973c13e7b468709@thread.tacv2/1669304281942?tenantId=1ad22c6d-2f08-4f05-a0ba-e17f6ce88380&groupId=17b1a2dc-67fb-4a49-a2ed-dd1344321439&parentMessageId=1669304281942&teamName=Communities%20of%20Practices&channelName=CX%20-%20CoP%20DevSecOps&createdTime=1669304281942&allowXTenantAccess=false).
- argo project added on beta env
- vault secret added for team on beta env

chore: onboard managed-identity-wallet beta env

---

environments/core/applicationsets/argo-applicationset.yaml

change TargetRevision to tag ArgoCD-v2.4.16_AVP-v1.13.0
Draft until [this PR](https://github.com/catenax-ng/k8s-cluster-stack/pull/245) is approved as it is related.

feat: change targetrevision for all clusters

---

apps/argocd/base/avp-argocd-cm.yaml
environments/core/applicationsets/argo-applicationset.yaml

ArgoCD 2.4 introduces an automatic prefix for user supplied environment variables. This applies to custom plugin configurations that we currently have. Therefore the `helm_args` variable we use with the AVP plugin does not work and therefore custom values.yaml files cannot be applied to the deployment.
Plans to fix and test:
1. Already [added an app](https://argo.devsecops-testing.demo.catena-x.net/applications/product-traceability-foss-frontend?view=tree&resource=) to the `devsecops-testing` cluster and it is showing no resources (as intended).
2. Point `devsecops-testing` argo config to this branch and enable the changes I made
3. Sync the app again and see if the problems are fixed
4. Point `devsecops-testing` back to the original branch
5. Merge and apply changes to all clusters
TEST …

fix: argocd 2.4 env variable breaking change

---

terraform/100_team_onboarding/main.tf

Adding new team puris and two gh repositories.
repository names: 
- product-puris-frontend
-  product-puris-backend
See https://jira.catena-x.net/browse/A1ODT-1083
`terraform apply` not performed, will be done after PR approval. `terraform plan` behave as expected:
```
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:
~ resource "github_team" "teams" {
~ etag          = "W/\"b2302ec9be04aa91939d55ecf17b5216d1d7ffa2b2e5e020018c82d196ea9891\"" -> "W/\"0bef818a7faf25d0f14052289a21d9ec8a64cb0ab24a1dcd2aa52a1b703d08a3\""
id            = "5765033"
name          = "argocdadmins"
}
~ resource "github_team" "teams" {
~ etag          = …
```

Onboard new GitHub Team + New repository (2x) A1ODT-1083

---

environments/core/applicationsets/ingress-applicationset.yaml

Set ArgoCD Applicationset for ingress-nginx to Git Tag `ingress-nginx-v4.2.3` instead of `HEAD` to be able to test other versions on _devsecops-testing_ cluster.
Referenced tag already created and points to the #PR186 which represents the latest changes in ingress configuration:
```shell
$ git show ingress-nginx-v4.2.3
tag ingress-nginx-v4.2.3
Tagger: Carsten Lenz <carsten.lenz@mercedes-benz.com>
Date:   Mon Dec 19 12:25:58 2022 +0100
Helm Chart version 4.2.3
appVersion 1.3.0
Current config as of 19.12.2022
commit 2586c1dd89fb0a67cfa7abe6fa48d6dffc1a5b5f (tag: ingress-nginx-v4.2.3)
Author: sgrigar <108792047+sgrigar@users.noreply.github.com>
Date:   Mon Aug 29 14:16:07 2022 +0200
fix: add annotation for health check probe for K8S version >= 1.24 (#186)
Co-authored-by: GRIGARS …
```

chore: introduce Git Tag for ingress-nginx

---

terraform/02_devsecops-testing_cluster/terraform.tfvars

New version is 1.24.6
Terraform plan output:
```
~ resource "azurerm_kubernetes_cluster" "aks_cluster" {
id                                  = "/subscriptions/899135fc-19c6-47cb-82f1-0230af7b99b5/resourcegroups/cx-devsecops-testing-rg/providers/Microsoft.ContainerService/managedClusters/cx-devsecops-testing-aks"
~ kubernetes_version                  = "1.24.3" -> "1.24.6"
name                                = "cx-devsecops-testing-aks"
tags                                = {}
~ default_node_pool {
name                         = "default"
~ orchestrator_version         = "1.24.3" -> "1.24.6"
tags                         = {}
}
}
~ resource "azurerm_resource_group" "default_resource_group" {
id       = …
```

build: upgrade devsecops-testing k8s version

---

apps/argocd/base/kustomization.yaml

Update ArgoCD Version to 2.4.18.

chore: bump ArgoCD Version to 2.4.18

---

environments/core/applicationsets/argo-applicationset.yaml

Install new ArgoCD Version on production servers

chore: bump ArgoCD version on prod servers

---

terraform/100_team_onboarding/main.tf

Add new repo to catena-x ng.
terraform plan runs as expected, but hasn't been applied. Will be after merging to main:
```shell
+ resource "github_repository" "repositories" {
+ allow_auto_merge            = false
+ allow_merge_commit          = true
+ allow_rebase_merge          = true
+ allow_squash_merge          = true
+ archived                    = false
+ auto_init                   = true
+ default_branch              = (known after apply)
+ delete_branch_on_merge      = true
+ etag                        = (known after apply)
+ full_name                   = (known after apply)
+ git_clone_url               = (known after apply)
+ has_downloads               = true
+ has_issues                  = false
+ has_projects                = …
```

chore: new repository product-behaviour-twin-minio

---

terraform/100_team_onboarding/main.tf

New forked repo tx-bpdm.
Terraform plan as expected (after terraform import):
```shell
~ resource "github_repository" "repositories" {
~ auto_init                   = false -> true
~ delete_branch_on_merge      = false -> true
~ has_projects                = true -> false
~ has_wiki                    = true -> false
id                          = "tx-bpdm"
name                        = "tx-bpdm"
~ vulnerability_alerts        = false -> true
}
+ resource "github_team_repository" "team-repository-access" {
+ etag       = (known after apply)
+ id         = (known after apply)
+ permission = "maintain"
+ repository = "tx-bpdm"
+ team_id    = "5788667"
}
Plan: 1 to add, 1 to change, 0 to destroy.
```

chore: add eclipse fork to terraform

---

terraform/modules/aks_cluster/main.tf

A migration scenario from service_principal to identity is supported. When upgrading service_principal to identity, your cluster's control plane and addon pods will switch to use managed identity, but the kubelets will keep using your configured service_principal until you upgrade your Node Pool.
To upgrade nodepool, run (example):
az aks nodepool upgrade --name default --resource-group cx-devsecops-testing-rg --cluster-name cx-devsecops-testing-aks --node-image-only

feat: aks control plane to use managed identity

---

environments/core/applicationsets/kube-prometheus-stack-applicationset.yaml

no longer needed as HEAD contains all the changes of the branch in the meantime

chore: reverted applicationset revision to HEAD

---

.github/workflows/helm-chart-release.yaml
charts/catena-cluster-stack/.helmignore
charts/catena-cluster-stack/Chart.yaml
charts/catena-cluster-stack/README.md
charts/catena-cluster-stack/templates/dns-config-secret.yaml
charts/catena-cluster-stack/templates/tls-certificate.yaml
charts/catena-cluster-stack/templates/tls-cluster-Issuer.yaml
charts/catena-cluster-stack/values.yaml

This PR introduces an umbrella chart containing our kubernetes stack components.
Cluster/environment specific configuration is intentionally left out, since this chart should be usable on any cluster.
Kyverno is currently missing in the umbrella chart, since we have to figure out, how we want to integrate the additional kustomization, that we do for kyverno on our environments

feat: add cluster stack umbrella chart #A1ODT-1170

---

apps/argocd/base/kustomization.yaml
apps/argocd/base/plugins/argo-vault-plugin.yaml

Bump ArgoCD to v2.4.21 to apply latest security (2.4.20) and bugfix (2.4.21) patch releases.

chore: bump ArgoCD to latest 2.4 patchlevel

---

environments/core/applicationsets/argo-applicationset.yaml

GH Tag ArgoCD-v2.4.21-c0_AVP-v1.13.1 already pushed to main.
Set targetRevision for clusters to new ArgoCD Version.

chore: update clusters to ArgoCD v2.4.21

---

apps/argocd/overlays/core/configmap/avp-argocd-cm.yaml
apps/argocd/overlays/core/kustomization.yaml
environments/core/applicationsets/argo-applicationset.yaml

Let core AVP config use vault-secret in argocd namespace (ENV cluster use `argocd-vault-plugin generate - -s $ARGOCD_APP_NAMESPACE:vault-secret`, core `argocd-vault-plugin generate - -s vault-secret`)

chore: avp setup core cluster

---

environments/core/applicationsets/argo-applicationset.yaml

To test ArgoCD 2.5 upgrade and new ArgoCD Vault Plugin approach (sidecar container instead of configMap setup), our devsecops-testing cluster will point to a feature branch instead of HEAD. Feature branch has been created from main and pushed.
After successful testing `targetRevision` for devsecops-testing cluster will be set back to HEAD again.
ArgoCD GH tag has been bumped (c3 → c4) to get changes applied.

chore: switch targetRevision for devsecops-testing cluster

---

environments/core/applicationsets/argo-applicationset.yaml

- edit targetRevision to ArgoCD-v2.4.22-c5_AVP-v1.13.1
- to bring all templates for notifications to all our clusters exept changes for AVP within devsecops-testing cluster

bump argo config version

---

environments/core/applicationsets/reflector-applicationset.yaml

Bump reflector version to fix reflector stop working, according to emberstack/kubernetes-reflector#292.

chore: update reflector to 7.0.147

---

apps/argocd/base/kustomization.yaml
environments/core/applicationsets/argo-applicationset.yaml

Bump ArgoCD version to `2.4.24` and GH tag to `ArgoCD-v2.4.22-c9_AVP-v1.13.1`

chore: update ArgoCD 2.4.24

---

apps/argocd/base/vault-plugin/argo-repo-server-sidecars.yaml

This is a fix pullrequest:
- add missing image to helm-kustomize sidecar
- align sidecar images to argocd image used in argocd-repo-server

fix: sidecar image for avp helm kustomize

---

apps/argocd/overlays/devsecops-testing/configmap/argo-notification-channels.yaml

update > Teams notification service
found out that if we add only one teams.service with 2 webhook urls in agro there will be only one service triggering both urls
so to separete these ones this PR to try out to generate 2 services for ms teams one for us and one for the desired product team
``` yaml
data:                                                                                                                                                                                                               
service.teams.irs: |                                                                                                                                                                                           
recipientUrls: …
```

fix: separate teams services into 2 recipients

---

apps/argocd/base/kustomization.yaml

Manage ArgoCD version and argocd-repo-server sidecar container images using kustomize functionality. Only limitation: keep newTag and ArgoCD Version in sync.
This will simplify maintenance of ArgoCD and the sidecar container images.

chore: keep sidecar images in sync with ArgoCD version using kustomize

---

apps/ingress-nginx/Chart.yaml

Bump to latest version. Checked Changelogs 4.3.2 → 4.5.2. I do not expect problems.
After merging to main branch, testing new version first on our devsecops-testing cluster. The ingress-nginx Argo App for each cluster has disabled autosync, so there is no damage expeted.

chore: bump ingress-nginx helm chart to version 4.5.2

---

apps/argocd/base/argo-notification-cm.yaml
apps/argocd/overlays/devsecops-testing/configmap/argo-notification-channels.yaml
environments/core/applicationsets/argo-applicationset.yaml

- moved default MS Teams Channel to Argo Cd base that every cluster has the possibility 
- bumped config version for Argo Cd Set-Up

chore: add our MS Teams channel to argo default base in cm + bump applicationset config version

---

apps/argocd/base/kustomization.yaml
apps/argocd/base/vault-plugin/argo-repo-server-sidecars.yaml
environments/core/applicationsets/argo-applicationset.yaml

Bump versions:
- ArgoCD 2.6.6 → 2.6.7
- AVP 1.13.1 → 1.14.1

chore: update ArgoCD (2.6.7) and AVP  (1.14.0)

---

apps/argocd/base/vault-plugin/vault-plugin-cm.yaml
environments/core/applicationsets/argo-applicationset.yaml

This will fix ArgoCD Apps with no resources, when App source is a helm chart with dependencies.
This fix has been manually applied to DEV/INT/BETA environment to solve issue reported by Lukas Römer.

fix: add init section

---

environments/core/applicationsets/argo-applicationset.yaml

For fixing vault plugin sidecar configs for discovery.

chore: new tag ArgoCD-v2.6.7-c3_AVP-v1.14.0

---

environments/core/applicationsets/argo-applicationset.yaml

- introduce new config version ArgoCD-v2.6.7-c4_AVP-v1.14.0

chore:bump to version ArgoCD-v2.6.7-c4_AVP-v1.14.0

---

apps/kube-prometheus-stack/dashboards/maintenance.json
apps/kube-prometheus-stack/templates/dashboards.yaml

The feature would configure a new grafana dashboard for the maintenance application. Will test is first on the devsecops-testing cluster.

feat: add maintenance grafana dashboard

---

environments/core/applicationsets/kube-prometheus-stack-applicationset.yaml
environments/core/applicationsets/kyverno-applicationset.yaml

Remove plugin names from the `kyverno` and `kube-prometheus-stack` applicaitonsets to fix them in argocd and use the auto discover feature of the sidecars.

fix: kyverno, prometheus-stack appset plugin setup

---

environments/core/applicationsets/argo-applicationset.yaml

Target revision for clusters changed to ArgoCD-v2.6.7-c5_AVP-v1.14.0

chore: new tag ArgoCD-v2.6.7-c5_AVP-v1.14.0

---

apps/kube-prometheus-stack/kustomization.yaml

Kustomize was running into an error as the new sidecars have `--include-crds` argument in the `helm template` command and we added the CRDs manually as well. This would result in a duplication of resources.

fix: remove manual crds from kube-prom-stack

---

apps/argocd/base/kustomization.yaml
environments/core/applicationsets/argo-applicationset.yaml

Bump ArgoCD to 2.6.8 and set applicationSet `targetRevision` to new Tag `ArgoCD-v2.6.8-c0_AVP-v1.14.0`.

chore: bump ArgoCD to 2.6.8

---

environments/core/kustomization.yaml

To enable new STABLE cluster, clusterSecret needs to be activated in `kustomization.yaml`.

chore: add clusterSecret

---

environments/core/applicationsets/certmanager-applicationset.yaml

Remove AVP plugin definition from `source` to get applicationSet back working.

chore: remove AVP

---

environments/core/applicationsets/kube-prometheus-stack-applicationset.yaml

Without this option the CDR installation fails with error:
```
one or more objects failed to apply, reason:
CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid:
metadata.annotations: Too long: must have at most 262144"
...
```
enabling syncOption `serversideapply=true` solves this by running `kubectl apply --server-side ...` instead of `kubectl apply ...`. see [ArgoCD docu](https://argo-cd.readthedocs.io/en/release-2.6/user-guide/sync-options/#server-side-apply).

fix: add syncOption `ServerSideApply=true`

---

apps/argocd/base/kustomization.yaml
environments/core/applicationsets/argo-applicationset.yaml

Upgrading argoCD to latest version 2.6.10

chore: upgrading argocd to 2.6.10

---

environments/core/applicationsets/kube-prometheus-stack-applicationset.yaml

chore: revert kube-prometheus applicationset to point to HEAD for DevSecOps testing cluster

---

apps/kube-prometheus-stack/dashboards/portal.json
apps/kube-prometheus-stack/dashboards/product-portal.json
apps/kube-prometheus-stack/templates/dashboards.yaml

Added a dashboard to display the following data for the portal services:
- the last errors that occured
- the amount of errors per statusCode
- the warnings that occured
- the avg elapsed time of the requests per service
To have a better overview of the errors and warnings that appear within the portal services
N/A - Jira Issue: CPLP-1849

feat(dashboard): add dashboard for portal service overview

---

apps/argocd/README.md

Documentation seems to be outdated and the file path link doesn't work anymore, giving 404.
Fixing that with a proper yaml path.

fix: update path to a file keeping AVP version

---

environments/core/applicationsets/certmanager-applicationset.yaml

Fixes https://github.com/eclipse-tractusx/sig-infra/issues/195

chore:  applicationset update for devsecops-testing cluster certmanager upgrade

---

apps/certmanager/Chart.yaml
environments/core/applicationsets/certmanager-applicationset.yaml

Fixes https://github.com/eclipse-tractusx/sig-infra/issues/195

chore: certmanager upgrade to 1.12.2 on all clusters

---

apps/ingress-nginx/Chart.yaml
environments/core/applicationsets/ingress-applicationset.yaml

- ingress-nginx upgrade to 4.7.1 on all clusters
- revert ingress applicationset targetRevision to HEAD for devsecops-testing cluster
Updates https://github.com/eclipse-tractusx/sig-infra/issues/200

chore: ingress upgrade

---

apps/kube-prometheus-stack/dashboards/product-portal.json

Extend the portal-product dashboard with an overview of searchable logs for a specific app and log level
To have a better searchability of the logs within the portal-product dashboard
N/A - Jira Issue: CPLP-3089

chore: add logs view to product-portal dashboard

---

apps/argocd/base/kustomization.yaml
apps/argocd/base/vault-plugin/argo-repo-server-sidecars.yaml
environments/core/applicationsets/argo-applicationset.yaml

Update ArgoCD minor version from 2.6 to 2.7. Stages will be updated after GH tag ArgoCD-v2.7.13-c0_AVP-v1.16.1 is available. The tag will be available after test has been finished on devsecops-testing-cluster
Upgrading info:
https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.6-2.7/
What's new in ArgoCD 2.7:
https://www.youtube.com/watch?v=00KxYdJKrSo
System team ticket: https://github.com/eclipse-tractusx/sig-infra/issues/239

chore: update argocd to 2.7 and avp to 1.16.1

---

apps/argocd/base/kustomization.yaml
commitlint.config.js
environments/core/applicationsets/argo-applicationset.yaml
package-lock.json

Updating ArgoCD to latest 2.7 patch release 2.7.14. This PR also contains some adjustments to pre-commit hook configuration.
eclipse-tractusx/sig-infra#239

chore: update ArgoCD patch version to 2.7.14

---

apps/argocd/base/argocd-cm.yaml
environments/core/applicationsets/kyverno-applicationset.yaml

Add Kyverno specific settings to `argocd-cm` confimap and point DevSecOps-Testing Cluster to a branch to install Kyverno from. 
Related to eclipse-tractusx/sig-infra#315

chore: update ArgoCD config to prepare kyverno deployment

---

environments/core/applicationsets/argo-applicationset.yaml

Of corse I missed to bump the targetRevision for ArgoCD applicationset to enable the changes from previous PR #424.
GH Tag does not yet exists and will be created on the merge commit and pushed to main branch after this PR has been merged.

chore: bump targetRevision due to config changes

---

apps/kyverno/values.yaml

For whatever reason the automatic determination of api-resource version for podDisruptionBudget fails. The Helm Chart provides a way to set apiVersion for that.
ArgoCD error was:
```
The Kubernetes API could not find version "v1beta1" of policy/PodDisruptionBudget for
requested resource kyverno/kyverno-background-controller. 
Version "v1" of policy/PodDisruptionBudget is installed on the destination cluster.
```

chore: fix api resource version

---

apps/kyverno/values.yaml

deploy the kyverno dashboard(s) to the kube-prometheus-stack namespace. In a second step the kube-prometheus-stack setup needs adjustments to implement this dashboard into grafana.

chore: deploy kyverno dashboard to monitoring ns

---

apps/kyverno/values.yaml

Enable `serviceMonitor` for Kyverno Controller to get Grafana dashboard to run.

chore: enable serviceMonitor

---

environments/core/applicationsets/argo-applicationset.yaml
environments/core/applicationsets/kyverno-applicationset.yaml

- set devsecops-testing cluster to dedicated targetRevision (to be pushed) for dev/testing/debug purpose
- remove unnecessary helm_args variable
- remove unused applicationSet syncPolicy settings
- bump ArgoCD GH Tag (to be pushed after PR merge)

chore: refactor kyverno-applicationset.yaml

---

environments/core/applicationsets/kyverno-applicationset.yaml
environments/core/applicationsets/kyverno-multisource-applicationset.yaml

To manage different pitfalls of kyverno deployment in our (ArgoCD) setup, refactor AppSet to use multi-source.
Reasons:
- As ApplicationSets support multi-source there is no need for creating an umbrella Helm Chart to deploy Kyverno. Refer to https://github.com/argoproj/argo-cd/blob/release-2.7/docs/user-guide/helm.md#values-files
- `apps/kyverno/` will only contain global values (`values.yaml`) and env specific values (`values-envName.yaml`).
- For `serviceMonitor` configuration, environment specific values are required.
For testing purpose, the multi-source AppSet is only applied to devsecops-testing cluster. In former Kyverno AppSet this cluster has been removed/commented.

feat: make kyverno a multi-source AppSet

---

.gitignore
environments/core/applicationsets/kyverno-multisource-applicationset.yaml

New Helm Chart Version: 3.0.7
New Kyverno Version: 1.10.5
```shell
helm search repo kyverno/kyverno --versions | head -n4
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
kyverno/kyverno                 3.1.0           v1.11.0         Kubernetes Native Policy Management
kyverno/kyverno                 3.0.7           v1.10.5         Kubernetes Native Policy Management
kyverno/kyverno                 3.0.6           v1.10.4         Kubernetes Native Policy Management
```
Kyverno 1.11.0 is available, but there is no release note available, omitting bumping to 1.11.0.
Add `DS_Store` to `.gitignore`

chore: bump kyverno to 1.10.5

---

environments/core/applicationsets/ingress-applicationset.yaml
environments/core/applicationsets/ingress-multisource-applicationset.yaml

Provide `ingress-nginx` as mult-source applicationset and enable it for devsecops-testing cluster for testing purpose. Branch `chore/ingress-as-multi-source-app` not yet pushed to repo.
eclipse-tractusx/sig-infra#350

chore: ingress-nginx as multi-source appset (step 1)

---

environments/core/applicationsets/ingress-applicationset.yaml
environments/core/applicationsets/ingress-multisource-applicationset.yaml

Add core cluster to new multi-source appset. Chart version is now configurable per generator list element.

chore: add core cluster to multi-source appset, enhance appset

---

environments/core/applicationsets/certmanager-applicationset.yaml

Adjust `ignoreDifferences` to fix OutOfSync status of resource `validatingwebhookconfiguration`:
eclipse-tractusx/sig-infra#366

chore: add ignoreDifferences for aks managed by

---

apps/kyverno/kyverno/values.yaml

PR to increase mem limits for kyverno-reports-controller due to crashing pods because of OOM issue.

fix: increase mem limit for kyverno-reports-controller

---

apps/kyverno/kyverno/values.yaml

PR to increase memory limit to 512Mi for  kyverno reports controller which is failing due to OOM at dev cluster.

fix: increase mem limit of kyverno reports controller

---

apps/argocd/base/kustomization.yaml
environments/core/applicationsets/argo-applicationset.yaml

Update our Argo CD instances to latest patch version of 2.7. The Argo CD instances will be updated after DEVSECOPS-TESTING cluster has been updated and tested successfully by pushing the new GH Tag `ArgoCD-v2.7.16-c0_AVP-v1.16.1` to the repository.
Argo CD Release Notes:
- https://github.com/argoproj/argo-cd/releases/tag/v2.7.15
- https://github.com/argoproj/argo-cd/releases/tag/v2.7.16

chore(deps): bump Argo CD to 2.7.16

---

apps/kube-prometheus-stack/MAINTENANCE.md
environments/core/applicationsets/kube-prometheus-stack-applicationset.yaml

PR reverts targetRevision to HEAD for devsecops-testing cluster + adds one more step to MAINTENANCE documentation for kube prometheus stack upgrade.
Fixes https://github.com/eclipse-tractusx/sig-infra/issues/422

fix: kube prometheus stack post upgrade

---

apps/certmanager/Chart.yaml
environments/core/applicationsets/certmanager-applicationset.yaml

Upgrade cert-manager to 1.14.4 on all clusters.
Updates https://github.com/eclipse-tractusx/sig-infra/issues/454

Upgrade certmanager 1.14.4
