- BOOTSTRAP.md
Add short instructions on how to create a new GitHub OAuth app and configure ArgoCD to use it
> Add instructions on how to set up GitHub login for ArgoCD

- apps/argocd/overlays/core/configmap/argo-cm.yaml
- apps/argocd/overlays/example/configmap/argo-cm.yaml
- apps/argocd/overlays/hotel-budapest/configmap/argo-cm.yaml
> fix argocd-cm.yaml in overlays

- apps/argocd/base/avp-argocd-cm.yaml
adding additional AVP Plugin for handling Helm with arguments
> added AVP Plugin for handling helm with args

- apps/argocd/base/avp-argocd-cm.yaml
helm 3 doesn't recognize `--install-crds`
> fix "Error: unknown flag: --install-crds"

- environments/hotel-budapest/argo-projects/product-example.yaml
- environments/hotel-budapest/avp-secrets/example-vault-secret.yaml
adding ArgoCD project and vault-secret for _product-team-example_ for testing/demo purpose
> Product team example project

- environments/hotel-budapest/argo-repos/product-semantics-repo.yaml
- environments/hotel-budapest/kustomization.yaml
add argo repo for private Github repo semantics, including ssh key from vault
> create repo secret for semantics

- apps/argocd/overlays/core/environments/dev.yaml
- apps/argocd/overlays/dev/configmap/argo-cm.yaml
- apps/argocd/overlays/dev/ingress/ingress-argocd.yaml
- apps/argocd/overlays/dev/kustomization.yaml
- environments/core/applicationsets/argo-applicationset.yaml
- environments/core/cluster-secrets/dev-cluster-secret.yaml
- environments/dev/avp-secrets/devsecops-team-vault-secret.yaml
- environments/dev/kustomization.yaml
manage dev cluster by core argo
> manage dev cluster by core cluster

- apps/vault/Chart.yaml
- apps/vault/values.yaml
feat: added dex with configuration
https://jira.catena-x.net/browse/A1ODT-518
> feat: added dex with configuration

- apps/argocd/base/avp-argocd-cm.yaml
- apps/vault/values.yaml
- environments/core/applications/vault-application.yaml
- environments/core/applicationsets/argo-applicationset.yaml
- environments/core/applicationsets/certmanager-applicationset.yaml
remove the requirement to put AVP_Secret as env var in argocd applications / applicationsets
> remove avp_secret from argocd applications/ applicationsets

- apps/argocd/overlays/core/environments/core.yaml
- apps/argocd/overlays/core/environments/dev.yaml
- apps/argocd/overlays/core/environments/example.yaml
- apps/argocd/overlays/core/environments/hotel-budapest.yaml
- environments/core/applicationsets/argo-applicationset.yaml
remove some configuration of avp_secret missing from last PR
> remove some configuration of avp_secret missing from last PR

- environments/dev/argo-projects/product-behaviour-twin-pilot.yaml
- environments/dev/avp-secrets/behaviour-twin-pilot-team-vault-secret.yaml
- environments/dev/kustomization.yaml
- environments/hotel-budapest/argo-projects/product-behaviour-twin-pilot.yaml
- environments/hotel-budapest/avp-secrets/behaviour-twin-pilot-team-vault-secret.yaml
- environments/hotel-budapest/kustomization.yaml
> onboarding team behaviour-twin-pilot

- apps/argocd/base/argocd-rbac-cm.yaml
please sync before merge to change the team name in GitHub at roughly the same time
> change team name to lower case

- terraform/02_vault/variables.tf
Changes are already applied to Vault
> fix: A1ODT-669 Fix dft secret engine / policy name mixup

- terraform/02_team_onboarding/main.tf
> Import product-knowledge repository to terraform

- environments/dev/argo-projects/product-behaviour-twin-pilot.yaml
- environments/dev/argo-projects/product-bpdm.yaml
- environments/dev/argo-projects/product-catenax-at-home.yaml
- environments/dev/argo-projects/product-data-format-transformer.yaml
- environments/dev/argo-projects/product-data-integritiy-demonstrator.yaml
- environments/dev/argo-projects/product-dft.yaml
- environments/dev/argo-projects/product-esc-backbone.yaml
- environments/dev/argo-projects/product-essential-services.yaml
- environments/dev/argo-projects/product-example.yaml
- environments/dev/argo-projects/product-explorer.yaml
- environments/dev/argo-projects/product-knowledge.yaml
- environments/dev/argo-projects/product-managed-identity-wallets.yaml
- environments/dev/argo-projects/product-material-pass.yaml
- environments/dev/argo-projects/product-semantics.yaml
- environments/dev/argo-projects/product-test-data-generator.yaml
- environments/dev/argo-projects/product-traceability-foss.yaml
- environments/dev/argo-projects/product-traceability-irs.yaml
- environments/dev/argo-projects/product-value-added-service.yaml
as more and more teams are requesting -pen namespaces on dev, I took the liberty to create this pull request to create them for all teams and suggest to put it in the team onboarding process (as well as suggest looking into templating it for ease of future use)
> add -pen namespaces on dev for all teams

- environments/dev/argo-projects/product-esc-backbone.yaml
- environments/hotel-budapest/argo-projects/product-esc-backbone.yaml
- environments/hotel-budapest/argo-projects/product-essential-services.yaml
in ArgoCD config for dev and int for project-esc-backbone
> PILOT: add persistent volumes to cluster scoped resources whitelist

- environments/core/applications/gh-org-checks-application.yaml
- environments/core/kustomization.yaml
currently the checks consist of 
- readme check for all repositories in the org
> add gh org checks

- terraform/02_team_onboarding/main.tf
fix product-portal-cd gh pages setting
> remove vault resource for trace-cs-webapp

- environments/core/applicationsets/argo-applicationset.yaml
bump ArgoCD Versions in production
> build: bump ArgoCD to v2.3.7 AppSet

- environments/dev/argo-projects/business-partner-certificates.yaml
- environments/dev/argo-projects/product-et-demonstrators.yaml
- environments/dev/avp-secrets/business-partner-certificates-team-vault-secret.yaml
- environments/dev/avp-secrets/et-demonstrators-team-vault-secret.yaml
- environments/dev/kustomization.yaml
- environments/hotel-budapest/argo-projects/business-partner-certificates.yaml
- environments/hotel-budapest/argo-projects/product-et-demonstrators.yaml
- environments/hotel-budapest/avp-secrets/business-partner-certificates-team-vault-secret.yaml
- environments/hotel-budapest/avp-secrets/et-demonstrators-team-vault-secret.yaml
- environments/hotel-budapest/kustomization.yaml
- terraform/100_team_onboarding/main.tf
a1odt-912 onboard product-et-demonstrators
a1odt-915 onboard product-business-partner-certificates
> Chore: a1odt-912 onboard product-et-demonstrators, a1odt-915 onboard product-business-partner-certificates

- environments/pre-prod/argo-projects/product-bpdm.yaml
- environments/pre-prod/argo-projects/product-daps.yaml
- environments/pre-prod/argo-projects/product-managed-identity-wallets.yaml
- environments/pre-prod/argo-projects/product-portal.yaml
- environments/pre-prod/argo-projects/product-sldt.yaml
> fix: revert permissions

- environments/dev/argo-projects/product-business-partner-certificates.yaml
- environments/hotel-budapest/argo-projects/product-business-partner-certificates.yaml
pen namespace was wrong defined
> fix: A1ODT-915 renamed pen namespace

- terraform/100_team_onboarding/main.tf
doc: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/team_repository#permission
> fix: change repository permission to from 'write' to 'push'

- environments/dev/kustomization.yaml
- environments/hotel-budapest/kustomization.yaml
Enable in `kustomization.yaml` to onboard new team to ArgoCD.
> chore: onboard new team to ArgoCD

- environments/core/applicationsets/argo-applicationset.yaml
after successful test on devsecops-testing cluster, bump the other productive servers
> feat: bump remaining argocd servers

- terraform/100_team_onboarding/main.tf
Terraform plan not yet applied
> Reduce product-portal access to read on frontend-registration A1ODT-950

- apps/certmanager/Chart.yaml
https://jira.catena-x.net/browse/A1ODT-1005
> build: update cert-manager 1.7.2 to 1.7.3

- terraform/100_team_onboarding/main.tf
Onboard new product. terraform is not applied, will be after merge to _main_ branch.
> chore: onboard new product product-r-strategy-assistant (A1ODT-1011)

- terraform/100_team_onboarding/main.tf
> chore: set prduct-esc-backbone-blockexplorer to private #A1ODT-964

- environments/dev/argo-projects/product-r-strategy-assistant.yaml
- environments/dev/avp-secrets/r-strategy-assistant.yaml
- environments/dev/kustomization.yaml
- environments/hotel-budapest/argo-projects/product-r-strategy-assistant.yaml
- environments/hotel-budapest/avp-secrets/r-strategy-assistant.yaml
- environments/hotel-budapest/kustomization.yaml
Onboard new GH Team to ArgoCD → A1ODT-1011
> chore: onboard team product-r-strategy-assistant

- apps/argocd/README.md
Added detailed documentation how to update ArgoCD and AVP
> Add maintenance docutmentation for ArgoCD/AVP

- terraform/100_team_onboarding/.terraform.lock.hcl
- terraform/100_team_onboarding/main.tf
In this PR, the terraform code is update to manage the forked repo from GitHub organisation "eclipse-tractusx"
> feat: A1ODT-1029 start to manage forked repo from org eclipse-tractusx from our terraform code

- .github/workflows/kics.yml
- .github/workflows/trivy.yml
- .github/workflows/vault-deploy.yaml
> chore: bump GH Actions versions

- environments/core/applicationsets/argo-applicationset.yaml
Change to fix/argo_2.4_env_variable_breaking_change for testing.
> test: change devsecops-testing targetRevision

- terraform/100_team_onboarding/main.tf
New repos and team repo access tx-dft-frontend, tx-dft-backend 
Also enabled gh-pages for product-traceability-foss-backend
> chore: fork dft from eclipse

- terraform/100_team_onboarding/.terraform.lock.hcl
- terraform/100_team_onboarding/main.tf
Adding new repositories for BPDM. There have been made some changes to other repos, due to previous problems:
- tx-portal-frontend
Disabled Branch protection as it will recreate the CODEOWNER file which caused problem. I'll recreate the branch protection manually after `terraform apply`
`terraform apply` not performed, will be done after PR approval. `terraform plan` behave as expected, except of deletion of branch protection:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place
- destroy
- resource "github_branch_protection" "branch_protection" {
- allows_deletions                = false -> null
- allows_force_pushes …
```
> Onboard new Repositories for BPDM

- environments/pre-prod/argo-apps/apps-wave-a.yaml
> chore: change source.path to new wave-a location

- environments/pre-prod/argo-apps/apps-wave-b.yaml
init wave-b deployment from k8s-cluster-stack
> chore(add): add apps-of-apps for wave-b

- environments/pre-prod/argo-projects/product-item-relationship-service.yaml
- environments/pre-prod/avp-secrets/item-relationship-service-vault-secret.yaml
Create ArgoCD project and AVP secret
> Pre-Prod onboarding: Item-Releationship-services

- terraform/100_team_onboarding/main.tf
fix: product-portal-backend - description
> fix: product-portal-backend - description Chore/a1 odt 1083

- environments/pre-prod/argo-projects/product-item-relationship-service.yaml
> chore: set correct GH teamname for groups

- terraform/100_team_onboarding/main.tf
> chore: cplp-1420 - deprecate product-portal-cd

- apps/ingress-nginx/Chart.yaml
- apps/ingress-nginx/values-beta.yaml
- apps/ingress-nginx/values-core.yaml
- apps/ingress-nginx/values-dev.yaml
- apps/ingress-nginx/values-devsecops-testing.yaml
- apps/ingress-nginx/values-hotel-budapest.yaml
- apps/ingress-nginx/values-pre-prod.yaml
- apps/landing-page/Chart.yaml
- apps/landing-page/values-beta.yaml
- apps/landing-page/values-core.yaml
- apps/landing-page/values-dev.yaml
- apps/landing-page/values-devsecops-testing.yaml
- apps/landing-page/values-int.yaml
- apps/landing-page/values-pre-prod.yaml
- environments/core/applicationsets/ingress-applicationset.yaml
- environments/core/applicationsets/landing-page-applicationset.yaml
- environments/core/kustomization.yaml
Ingress controller got a service/k8s-landing-page configured as defaultBackend.
Landing page added to a new ArgoCD applicationSet
> chore: ingress defaultBackend and landing-page

- terraform/100_team_onboarding/main.tf
> chore: cplp-1852 - deprecate product-portal-iam

- environments/dev/argo-repos/product-behaviour-twin-minio.yaml
- environments/dev/kustomization.yaml
Add private repo `product-behaviour-twin-minio` to ArgoCD/DEV Cluster
> chore: add private repo to ArgoCD

- environments/dev/argo-repos/product-behaviour-twin-minio.yaml
> chore: fix repo link

- terraform/100_team_onboarding/main.tf
Add 2 new repos for System team
> chore: new repos

- terraform/100_team_onboarding/main.tf
forking managed-identity-wallets to NG GH org.
> chore: new fork 

- terraform/100_team_onboarding/main.tf
Forking tx-traceability-foss-frontend and tx-traceability-foss-backend.
terraform import done. Terraform plan as expected.
> chore: new tx fork

- terraform/100_team_onboarding/main.tf
New repo for portal.
`terraform plan`:
```
+ resource "github_repository" "repositories" {
+ allow_auto_merge            = false
+ allow_merge_commit          = true
+ allow_rebase_merge          = true
+ allow_squash_merge          = true
+ archived                    = false
+ auto_init                   = true
+ default_branch              = (known after apply)
+ delete_branch_on_merge      = true
+ etag                        = (known after apply)
+ full_name                   = (known after apply)
+ git_clone_url               = (known after apply)
+ has_downloads               = true
+ has_issues                  = false
+ has_projects                = false
+ has_wiki                    = false
+ html_url                    = (known …
```
> chore: new repo

- apps/argocd/base/kustomization.yaml
- environments/core/applicationsets/argo-applicationset.yaml
> chore: bump Argocd version

- apps/argocd/base/kustomization.yaml
- environments/core/applicationsets/argo-applicationset.yaml
- add file to strategic merge
- bump targetRevisionTag to c6
> add-specific-ressources to kustomization for argo-applicationset

- environments/core/applicationsets/argo-applicationset.yaml
- cleared out sync options for argo
- bumped config version tag
> remove sync options for argo-application-set

- environments/core/applicationsets/maintenance-dashboard-app-applicationset.yaml
The new maintenance dashboard will be added to the devsecops testing cluster.
> chore: add maintenance dash to devsecops-testing

- apps/argocd/base/argocd-notifications-secrets.yaml
- apps/argocd/overlays/devsecops-testing/configmap/argo-notification-channels.yaml
For a better understanding renamed the channel *name*
> chore: rename system-team MS Teams channel for better understanding

- apps/argocd/overlays/core/configmap/vault-plugin-cm.yaml
Adjusted the configs for the plugins to the config in base.
> fix: adjust cmp-plugin core overlay configmap

- apps/tls/values-tls-stable.yaml
- environments/core/applicationsets/app-dashboard-applicationset.yaml
- environments/core/applicationsets/certmanager-applicationset.yaml
- environments/core/applicationsets/ingress-applicationset.yaml
- environments/core/applicationsets/kube-prometheus-stack-applicationset.yaml
- environments/core/applicationsets/kyverno-applicationset.yaml
- environments/core/applicationsets/landing-page-applicationset.yaml
- environments/core/applicationsets/loki-applicationset.yaml
- environments/core/applicationsets/reflector-applicationset.yaml
- environments/core/applicationsets/tls-applicationset.yaml
Install default stack on new cluster `stable`.
> chore: onboard new cluster

- apps/ingress-nginx/values-stable.yaml
- apps/kube-prometheus-stack/values-stable.yaml
- apps/landing-page/values-stable.yaml
Add cluster specific values to Helm charts.
> chore: push cluster specific configuration

- environments/core/applicationsets/argo-applicationset.yaml
- environments/core/applicationsets/kube-prometheus-stack-applicationset.yaml
Preparation for k8s prometheus stack, changing prometheus applicationset and argocd applications.
> chore: preparation for k8s prometheus stack

- environments/core/applicationsets/ingress-applicationset.yaml
Test ingress-nginx upgrade on devsecops-testing cluster.
> chore: ingress-nginx upgrade on devsecops-testing cluster

- apps/loki/values.yaml
Increase Loki Disk size to fix current issue eclipse-tractusx/sig-infra#216
> chore(loki): increase disk size from 50 to 100Gi

- apps/kube-prometheus-stack/dashboards/product-portal.json
Adjust query for the searchable log of the product portal dashboard
Currently the errors aren't searchable because of the formatting of the query
N/A - Jira Issue: CPLP-1849
> fix: adjust searchable overview query

- apps/kube-prometheus-stack/Chart.yaml
- apps/kube-prometheus-stack/values-beta.yaml
- apps/kube-prometheus-stack/values-core.yaml
- apps/kube-prometheus-stack/values-dev.yaml
- apps/kube-prometheus-stack/values-devsecops-testing.yaml
- apps/kube-prometheus-stack/values-hotel-budapest.yaml
- apps/kube-prometheus-stack/values-pre-prod.yaml
- apps/kube-prometheus-stack/values-stable.yaml
- environments/core/applicationsets/kube-prometheus-stack-applicationset.yaml
- upgrade kube-prometheus-stack on all envs
- fixate the generated loki uid on all envs
> chore: apply changes to remaining environments

- .gitignore
- apps/kyverno/Chart.yaml
- apps/kyverno/values.yaml
- environments/core/applicationsets/kyverno-applicationset.yaml
Upgrade Kyverno to v1.10 using Helm Chart v3.
> chore: upgrade kyverno to v1.10

- apps/kyverno/values.yaml
Update Kyverno configuration to meet AKS platform specific requirements.
For more details, refer to documentation:
- https://kyverno.io/docs/installation/platform-notes/#notes-for-aks-users 
- https://learn.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces
> chore: add AKS specific config

- apps/kyverno/values.yaml
Settings according to documentation: https://kyverno.io/docs/installation/methods/#high-availability
> chore: make kyverno high available

- apps/kube-prometheus-stack/dashboards/product-portal.json
adjust namespace for product-portal queries
adjust error view for product-portal dashboard
With the upgrade of postgres the product-portal has been moved to another namespace, with this PR the dashboard and it's queries are aligned
N/A - Jira Issue: CPLP-3332
> fix(portal): adjust namespace to iam

- environments/core/applicationsets/kyverno-multisource-applicationset.yaml
fix malformed addressing of value files for core and int env.
> fix: fix appset for core and int env

- environments/core/applicationsets/kube-prometheus-stack-applicationset.yaml
PR to prepare and test applicationset at devsecops for kube-prometheus-stack upgrade.
> chore: change targetRevision for devsecops kube-prometheus-stack appset

- apps/kube-prometheus-stack/Chart.yaml
- apps/kube-prometheus-stack/values.yaml
bump kube-prometheus-stack to 56.6.2
> chore: bump kube-prometheus-stack to 56.6.2

- environments/core/applicationsets/certmanager-applicationset.yaml
Upgrade cert-manager to 1.14.4 at devsecops cluster.
> Upgrade CM at devsecops cluster

- environments/core/applicationsets/ingress-multisource-applicationset.yaml
Updates https://github.com/eclipse-tractusx/sig-infra/issues/457
> Bump ingress nginx to 4.10.0 at devsecops cluster

- environments/core/applicationsets/ingress-multisource-applicationset.yaml
Upgrade ingress to 4.10.0
Updates https://github.com/eclipse-tractusx/sig-infra/issues/457
> Bump ingress all clusters
